var DistroIcons = [
	{ PATH: '/Resources/fedora-logo-symbolic.svg'},
    { PATH: 'start-here-symbolic'},
    { PATH: '/Resources/debian-logo-symbolic.svg'},
    { PATH: '/Resources/manjaro-logo-symbolic.svg'},
    { PATH: '/Resources/pop-os-logo-symbolic.svg'},
    { PATH: '/Resources/ubuntu-logo-symbolic.svg'},
    { PATH: '/Resources/arch-logo-symbolic.svg'},
    { PATH: '/Resources/opensuse-logo-symbolic.svg'},
    { PATH: '/Resources/raspbian-logo-symbolic.svg'},
    { PATH: '/Resources/kali-linux-logo-symbolic.svg'},
    { PATH: '/Resources/pureos-logo-symbolic.svg'},
    { PATH: '/Resources/solus-logo-symbolic.svg'},
    { PATH: '/Resources/budgie-logo-symbolic.svg'},
    { PATH: '/Resources/gentoo-logo-symbolic.svg'},
    { PATH: '/Resources/mx-logo-symbolic.svg'},
    { PATH: '/Resources/redhat-logo-symbolic.svg'},
    { PATH: '/Resources/voyager-logo-symbolic.svg'},
]